### ISSUE TITLE
hangs when searching for a plot by cadastral number

### ISSUE THREAD

**Issue by PG-577** [matmatamat/rosreestr-search-qgis-plugin_old_version#1]
зависает при поиске участка по кадастровому номеру

Версия QGIS | 3.24.1-Tisler | Ревизия | 5709b82461
-- | -- | -- | --
Версия Qt | 5.12.8
Версия Python | 3.8.10
Версия GDAL/OGR | 3.0.4
Версия PROJ | 6.3.1
Версия базы данных реестра EPSG | v9.8.6 (2020-01-22)
Версия GEOS при сборке | 3.8.0-CAPI-1.13.1 | Текущая версия GEOS | 3.8.0-CAPI-1.13.1
Версия SQLite | 3.31.1
Версия PDAL | 2.0.1
Версия PostgreSQL | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
Версия SpatiaLite | 4.3.0a
Версия QWT | 6.1.4
Версия QScintilla2 | 2.11.2
Версия ОС | Ubuntu 20.04.4 LTS
  |   |   |  
Включенные модули Python
quick_map_services | 0.19.29
rosreestr-search-qgis-plugin-master | 1.4
MetaSearch | 0.3.6
sagaprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99

</body></html>Версия QGIS
3.24.1-Tisler
Ревизия
[5709b82461](https://github.com/qgis/QGIS/commit/5709b82461)
Версия Qt
5.12.8
Версия Python
3.8.10
Версия GDAL/OGR
3.0.4
Версия PROJ
6.3.1
Версия базы данных реестра EPSG
v9.8.6 (2020-01-22)
Версия GEOS при сборке
3.8.0-CAPI-1.13.1
Текущая версия GEOS
3.8.0-CAPI-1.13.1 
Версия SQLite
3.31.1
Версия PDAL
2.0.1
Версия PostgreSQL
12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
Версия SpatiaLite
4.3.0a
Версия QWT
6.1.4
Версия QScintilla2
2.11.2
Версия ОС
Ubuntu 20.04.4 LTS

**Comment by matmatamat** [comment]
Напишите кадастровый номер, который вызвал ошибку.
Часто ошибки модуля возникают из-за некорректной работы pkk.rosreestr.ru
Спасибо!

Write the cadastral number that caused the error.
Often module errors occur due to incorrect operation of pkk.rosreestr.ru
Thanks!

**Comment by PG-577** [comment]
61:44:0061815:23

**Comment by matmatamat** [comment]
Ошибка устранена, переустановите модуль.

The error has been fixed. Reinstall the module.
